global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for an HTTP 200 response
    static_configs:
      - targets:
          - http://prometheus.io
          - https://prometheus.io
          # Replace with your blog app URL
          - http://your-blog-app-url.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115  # Blackbox Exporter address

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'jenkins'
    static_configs:
      - targets: ['your-jenkins-ip:8080']

  - job_name: 'sonarqube'
    static_configs:
      - targets: ['your-sonarqube-ip:9000']

  - job_name: 'nexus'
    static_configs:
      - targets: ['your-nexus-ip:8081']
